---
apiVersion: v1
kind: Namespace
metadata:
  name: shield-system 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-mongodb-config
  namespace: shield-system 
data:
  config.json: |
    {
      "mongo_uri": "mongodb://ricardo:AdminExample@mongo-1.shield.svc.cluster.local:32017/",
      "mongo_db": "shield",
      "cluster": "acc",
      "log_level": "debug",
      "falco": {
        "enabled": true,
        "namespace": "falco-system"
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-mongodb-controller
  namespace: shield-system 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-mongodb-controller
  template:
    metadata:
      labels:
        app: k8s-mongodb-controller
    spec:
      serviceAccountName: k8s-mongodb-controller
      containers:
        - name: controller
          image: ghcr.io/shield-scanner/controller/shield-controller:latest
          imagePullPolicy: Always
          env:
            - name: CONFIG_PATH
              value: "/config/config.json"
          volumeMounts:
            - name: k8s-mongodb-config
              mountPath: /config
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: k8s-mongodb-config
          configMap:
            name: k8s-mongodb-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-mongodb-controller
  namespace: shield-system 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-mongodb-controller
  namespace: shield-system
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["aquasecurity.github.io"]
    resources:
      [
        "vulnerabilityreports",
        "clustercompliancereports",
        "clusterconfigauditreports",
        "clusterinfraassessmentreports",
        "clusterrbacassessmentreports",
        "clustersbomreports",
        "clustervulnerabilityreports",
        "configauditreports",
        "exposedsecretreports",
        "infraassessmentreports",
        "rbacassessmentreports",
        "sbomreports",
      ]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-mongodb-controller
  namespace: shield-system 
subjects:
  - kind: ServiceAccount
    name: k8s-mongodb-controller
    namespace: shield-system 
roleRef:
  kind: Role
  name: k8s-mongodb-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-mongodb-controller
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["aquasecurity.github.io"]
    resources:
      [
        "vulnerabilityreports",
        "clustercompliancereports",
        "clusterconfigauditreports",
        "clusterinfraassessmentreports",
        "clusterrbacassessmentreports",
        "clustersbomreports",
        "clustervulnerabilityreports",
        "configauditreports",
        "exposedsecretreports",
        "infraassessmentreports",
        "rbacassessmentreports",
        "sbomreports",
      ]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["falco.security.io"]
    resources: ["falcos", "falcorules", "falcorulegroupses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-mongodb-controller
subjects:
  - kind: ServiceAccount
    name: k8s-mongodb-controller
    namespace: shield-system 
roleRef:
  kind: ClusterRole
  name: k8s-mongodb-controller
  apiGroup: rbac.authorization.k8s.io
