---
apiVersion: v1
kind: Service
metadata:
  name: mongo-1-nodeport
  namespace: shield-system 
spec:
  type: NodePort
  selector:
    app: mongo-1
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 32017

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: shield-system 
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: shield-system 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-1
  namespace: shield-system 
spec:
  selector:
    app: mongo-1
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-1
  namespace: shield-system 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-1
  template:
    metadata:
      labels:
        app: mongo-1
    spec:
      containers:
        - name: mongo
          image: mongo:7
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: ricardo
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: AdminExample
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 512Mi
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc
