apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shield-controller
  namespace: shield-system
  labels:
    app: shield-controller
subjects:
  - kind: ServiceAccount
    name: shield-controller
roleRef:
  kind: Role
  name: shield-controller
  apiGroup: rbac.authorization.k8s.io
