apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shield-controller
  namespace: shield-system
  labels:
    app: shield-controller
rules:
  - apiGroups: [""]
    resources: ["namespaces", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["aquasecurity.github.io"]
    resources:
      - vulnerabilityreports
      - clustercompliancereports
      - clusterconfigauditreports
      - clusterinfraassessmentreports
      - clusterrbacassessmentreports
      - clustersbomreports
      - clustervulnerabilityreports
      - configauditreports
      - exposedsecretreports
      - infraassessmentreports
      - rbacassessmentreports
      - sbomreports
    verbs: ["get", "list", "watch"]
